// Generated by CoffeeScript 1.12.2
(function() {
  describe("Writing Node with CoffeeScript", function() {
    return it("is easy to get started testing... or is it?", function() {
      return true;
    });
  });

}).call(this);
